displayName=Improved Loot Tracker
author=luisb
description=Shows received loot history and wiki-style potential drop tables.
tags=loot,drop-rate,wiki,pvm,raids,chest
plugins=com.loottableviewer.LootTableViewerPlugin
build=standard
